# Generated by Django 5.0.1 on 2024-01-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_answer_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="modify_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="modify_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
