# Generated by Django 5.0.1 on 2024-01-22 04:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_answer_voter_question_voter_alter_answer_author_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="latitude",
            new_name="count",
        ),
        migrations.RenameField(
            model_name="location",
            old_name="longitude",
            new_name="crime_danger",
        ),
    ]
