# Generated by Django 5.0.1 on 2024-01-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0007_rename_latitude_location_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="question_images/"
            ),
        ),
    ]
