# Generated by Django 5.0.1 on 2024-01-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0008_question_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="count",
            new_name="dawn_count",
        ),
        migrations.AddField(
            model_name="location",
            name="evening_count",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="morning_count",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="night_count",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
