# Generated by Django 5.0.1 on 2024-01-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0009_rename_count_location_dawn_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="afternoon_count",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
