# Generated by Django 5.0.1 on 2024-02-02 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0010_location_afternoon_count"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search_keyword", models.CharField(max_length=255)),
                ("search_time", models.CharField(max_length=50)),
                ("distance", models.IntegerField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_bookmark",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
